### ISSUE TITLE
Supported SOCKS method not found

### ISSUE THREAD

**Issue by megapegabot** [cfal/shoes#16]
hi my config:
```
- address: 0.0.0:1080
  protocol:
    type: socks
    username: admin
    password: admin
  rules:
    - mask: 0.0.0.0/0
      action: allow
      client_proxy: direct
```
im have err:
```
ERROR shoes::tcp_server] 172.17.0.1:56200 finished with error: Custom { kind: InvalidInput, error: "failed to setup server stream: Supported SOCKS method not found" }
```
request_cmd:  `curl -x socks5://localhost:1080 example.com`

If I understand correctly, there is support for socks5, but I can’t use it
