### ISSUE TITLE
[Bug]: Vless Over QUIC

### ISSUE THREAD

**Issue by radiumatic** [cfal/shoes#26]
I have a sing-box vless-over-QUIC server and `shoes` fails to work with it. I don't think connectivity is the problem as trying to open connections to nonexistent domains instantly results in an error, not to mention that the same configuration works with sing-box and the older version of Xray-core that had QUIC support.

```yaml
- address: 127.0.0.1:8888
  transport: tcp
  protocol:
    type: socks5
  rules:
    # Directly connect to 192.168.*
    - mask: 192.168.0.0/16
      action: allow
      client_proxy: direct
    # Forward all other connection requests through a Vmess WSS server.
    - mask: 0.0.0.0/0
      action: allow
      client_proxy:
        - address: "example.com:443"  # Replace with the actual server address and port
          protocol:
            type: vless
            user_id: "A UUID"  # Replace with your actual UUID
          transport: quic
          quic_settings:
            verify: true  # Whether to verify the server's certificate
            sni_hostname: "example.com"  # Optional SNI hostname; can be left unspecified
            alpn_protocols:
              - "h3"  # Specify the ALPN protocol; e.g., HTTP/3% 
```
The error:
```
[2024-10-15T15:13:41Z ERROR shoes::tcp_server] 127.0.0.1:49834 finished with error: Custom { kind: UnexpectedEof, error: "failed to setup client stream to www.google.com:443: early eof" }
```
