### ISSUE TITLE
loading config error

### ISSUE THREAD

**Issue by MeexReay** [cfal/shoes#27]
Config:

```yml
- address: 127.0.0.1:8081
  transport: tcp
  protocol:
    type: http
    username: admin
    password: 123456
  rules:
    - mask: 0.0.0.0/0
      action: allow
      client_proxy: direct
```

Error:

```
Failed to load server configs: Could not parse config file conf.yml as config YAML: data did not match any variant of untagged enum Config
```
