### ISSUE TITLE
The IPv6 address is not reachable.

### ISSUE THREAD

**Issue by shelmesky** [cfal/shoes#49]
I’m using an IPv6 address `2001:DC0:25F0:2222::5f` and port `23130` as the client address, but the `shoes` program throws an error saying it can’t connect.

```
Custom { kind: ConnectionRefused, error: "failed to setup client stream to content-autofill.googleapis.com:443: Connection refused (os error 111)" }
```

And I’ve confirmed that this IPv6 address is reachable with a ping on the current host.

Here is my configuration file:

```yaml
- address: 0.0.0.0:12345
  transport: tcp
  protocol:
    type: vmess
    cipher: aes-128-gcm
    user_id: 654def50-7001-4335-8169-880047943f40
  rules:
    - mask: 0.0.0.0/0
      action: allow
      client_proxy:
        address: 2001:DC0:25F0:2222::5f:23130
        protocol:
          type: vmess
          cipher: aes-128-gcm
          user_id: 654def50-7001-4335-8169-880047943f40
```

Is there something wrong with my configuration? 
The same configuration works fine with the IPv4 address.
